name: verify

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '17.x'
        cache: 'yarn'

    - name: Preparation
      run: yarn

    - name: Run test
      run: yarn test
